### ISSUE TITLE
Compilation Fails on Apple Silicon

### ISSUE THREAD

**Issue by Jesserc** [lmittmann/go-solc#39]
I'm encountering a compilation failure in the examples/console tests. The error says that the expected Solidity compiler version (0.8.21) is unknown. The same thing happens when I import the go-solc package in my project and try to use it.

Error Output:
```
--- FAIL: TestNewConsole (0.00s)
    console_test.go:19: Compilation failed: solc: unknown version "0.8.21"
FAIL
exit status 1
FAIL  examples/console    0.550s
```

**Comment by lmittmann** [comment]
Which OS, and CPU architecture are you using?

**Comment by Jesserc** [comment]
> Which OS, and CPU architecture are you using?

macOS, arm64

**Comment by lmittmann** [comment]
Unfortunately maxOS with ARM is currently not supported. `go-solc` fetches Solidity binaries from the official repo at https://binaries.soliditylang.org. Apple Silicon builds are still missing, see https://github.com/ethereum/solidity/issues/12291

A PR for allowing `go-solc` use the locally installed `solc` version is welcome.

**Comment by lmittmann** [comment]
Actually it looks like the most recent release v0.8.24 runs on arm as well. Will look into this

**Comment by lmittmann** [comment]
@Jesserc please give #40 a try

**Comment by lmittmann** [comment]
> Btw, do you have any idea if this method has less memory usage or overhead compared to using exec.Command to simply run solc and compile Solidity, without anything else intense?

there is only the overhead added by `go-solc`. Like adding `console.sol` to the compilation context.
